topic_custom_field_enabled:
  default: true
  client: true
  type: bool

topic_custom_field_name:
  default: admin_only
  client: false
  type: text

topic_custom_field_type:
  default: boolean
  client: false
  type: enum
  choices:
    - boolean
