plugins:
  topic_custom_field_enabled:
    default: true
    client: true

  topic_custom_field_name:
    default: 'admin_only'
    client: true

  topic_custom_field_type:
    default: 'boolean'
    type: enum
    choices:
      - string
      - integer
      - boolean
      - json
